_wandb:
    value:
        cli_version: 0.26.0
        e:
            x4k2tduzmc1315vzecedu92tdon93a3z:
                args:
                    - --data_dir
                    - data/NEU-CLS
                    - --project
                    - csc4005-lab1-neu-mlp
                    - --run_name
                    - dropout_0.5
                    - --optimizer
                    - adamw
                    - --lr
                    - "0.001"
                    - --weight_decay
                    - "0.0001"
                    - --dropout
                    - "0.5"
                    - --epochs
                    - "20"
                    - --batch_size
                    - "32"
                    - --img_size
                    - "64"
                    - --patience
                    - "5"
                    - --augment
                    - --use_wandb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "3144675328"
                        used: "339247104"
                email: nguyenvanhuy25021982@gmail.com
                executable: C:\Users\Huy\anaconda3\envs\csc4005-dl\python.exe
                git:
                    commit: 1854c4005179120c406a0a360dd5e14cc70541c9
                    remote: https://github.com/FIT-DNU-CS-16-01/csc4005-lab1-neu-mlp-VTV-24-1.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-d0b20f39-f9aa-83c4-8b78-463b550788c3
                host: DESKTOP-0CTHEO4
                memory:
                    total: "7879598080"
                os: Windows-10-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.10.20
                root: D:\Deep Learning\lab 1\csc4005-lab1-neu-mlp-VTV-24-1
                startedAt: "2026-04-15T03:03:56.786631Z"
                writerId: x4k2tduzmc1315vzecedu92tdon93a3z
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.0
            "8":
                - 3
            "12": 0.26.0
            "13": windows-amd64
augment:
    value: true
batch_size:
    value: 32
class_names:
    value:
        - Crazing
        - Inclusion
        - Patches
        - Pitted_Surface
        - Rolled-in_Scale
        - Scratches
data_dir:
    value: data/NEU-CLS
device:
    value: cpu
dropout:
    value: 0.5
epochs:
    value: 20
hidden_dims:
    value:
        - 512
        - 256
        - 64
img_size:
    value: 64
input_dim:
    value: 4096
lr:
    value: 0.001
num_classes:
    value: 6
num_workers:
    value: 0
optimizer:
    value: adamw
patience:
    value: 5
project:
    value: csc4005-lab1-neu-mlp
resolved_data_dir:
    value: D:\Deep Learning\lab 1\csc4005-lab1-neu-mlp-VTV-24-1\data\NEU-CLS_extracted
run_name:
    value: dropout_0.5
scheduler:
    value: none
seed:
    value: 42
test_size:
    value: 0.15
use_wandb:
    value: true
val_size:
    value: 0.15
weight_decay:
    value: 0.0001
